### ISSUE TITLE
Figure out what to do with image-heavy pages

### ISSUE THREAD

**Issue by autrice** [City-of-Bloomington/drupal-theme-cob#10]
See http://bloomington.in.gov/documents/viewDocument.php?document_id=3227  

Pages displaying past grant projects are not exceptionally heavy content (153 page views in 2016), but perhaps an important part of the grant process? Is there a better way to show this content? Solely using Facebook for this content excludes non-facebook users.

**Comment by charlesbrandt** [comment]
This is still an open issue. We've had requests for a gallery type of system for certain types of image heavy content 

(https://tarantula.bloomington.in.gov/documents/viewDocument.php?document_id=3227)

Part of this involves deciding how the images should be displayed (e.g. image info card?) The other part involves deciding how content managers add and organized the images (separate nodes?)

**Comment by rbdietz** [comment]
Parks is interested in this based on conversations today.  They need to be
able to sell their services and facilities.  Part of that is visual.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov
