### ISSUE TITLE
select dropdowns are white on white

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-theme-cob#100]
The search menu for PROMT programs under "Find Activities" has drop down menus to search by categories, but the font is white on a white background and you can't see the choices.

**Comment by inghamn** [comment]
This seems to only be happening in Chrome

**Comment by charlesbrandt** [comment]
https://bloomington.in.gov/parks

I only see this in Firefox on MacOS

**Comment by inghamn** [comment]
We should check that this is still happening.  If we hit all the browsers listed here, we can close this out.

- [ ] Firefox / Mac
- [ ] Chrome / Mac
- [ ] Safari / Mac
- [ ] Firefox / Windows
- [ ] Chrome / Windows
- [ ] Edge / Windows

**Comment by charlesbrandt** [comment]
I confirmed that all 3 browsers look good on Mac. (https://bloomington.in.gov/parks)

**Comment by inghamn** [comment]
The normalize CSS problem described above is indeed breaking things for Windows Chrome and Edge.

**Comment by inghamn** [comment]
Removed the CSS property from Factory Number One's normalize
