### ISSUE TITLE
Staff Directory formatting updates

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#101]
We need a page that lists all of the city staff approved for display on the website, not just route people to departments for this.  This could be at /contact/phone after the current text information.

**Comment by inghamn** [comment]
This already exists.  I think we just don't link to it from anywhere.

https://bloomington.in.gov/contact/directory

**Comment by rbdietz** [comment]
OK, we need to order the departments in a sensible way, format the name/job
title area, reach out to departments without contact information and put
this up with a card for Employee Directory





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by charlesbrandt** [comment]
I added a link to this from the /contact page. I still see the non-alphabetical on the live site.

**Comment by rbdietz** [comment]
Alphabetize the departments please.

**Comment by charlesbrandt** [comment]
Cliff just updated the production site to be alphabetized.

**Comment by rbdietz** [comment]
Please add a comma  between the contact's name and title, or or some other formatting

**Comment by rbdietz** [comment]
And table of contents

**Comment by rbdietz** [comment]
also the numbers are wrong.  This seems to only be displaying the main office numbers for everyone.

**Comment by rbdietz** [comment]
But maybe that's the way everyone wants it.
