### ISSUE TITLE
Review Validator issues for issues that need to be fixed

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#103]
https://validator.w3.org/nu/?showoutline=yes&showimagereport=yes&doc=https%3A%2F%2Fbloomington.in.gov%2F

div, image descriptions, headings

https://jigsaw.w3.org/css-validator/validator?uri=bloomington.in.gov&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en

**Comment by inghamn** [comment]
The actual HTML errors are nearly all realted to the Calendar markup we're using.  <div> is not allowed in <time>.  We'll need to replace them with spans.
