### ISSUE TITLE
Fix homepage rendering on IE/Edge

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#104]
On IE/Edge, the news section flows over in to the About Bloomington section:

![edge-homepage-20170628](https://user-images.githubusercontent.com/2225624/27650838-3b3341b6-5c04-11e7-97ac-f2d97d966a9b.PNG)

I know we'd like the news and events sections to line up ideally, but if this breaks other browsers it'd be better to make things work in all cases.

**Comment by inghamn** [comment]
It is definitely borked in IE 11.

**Comment by inghamn** [comment]
The CSS height and overflow ended up applying to the /news page as well.  On that page, we do, in fact, want to allow all the news items to show.
