### ISSUE TITLE
Bids

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#107]
We need to organize bid listing on the site.  We might need a bids document type to be able to aggregate across parks, public works, plan/trans, and other bids onto one page listing them all.

**Comment by quarterback** [comment]
https://bloomington.in.gov/rfp

I'll experiment with a guide page type that allows for attachments, info cards called a "bid page" where people can upload their own bids to the site without having us create the pages for them. It'll streamline the process.
