### ISSUE TITLE
Homepage News

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#109]
We need to improve the presentation of news on the home page.  Titles and teaser text are both flowing under their containers.

**Comment by rbdietz** [comment]
Events has this problem too.

**Comment by adabutch** [comment]
fixed & working on IE/edge/10 😄 

note: @inghamn using JS (cob.js) to truncate text ...

**Comment by charlesbrandt** [comment]
The latest update is a major improvement. For article summaries on the home page, when a content image is specified we have more room for a title. In this case, it would be nice to let the title fill more space before truncating. 
<img width="361" alt="screen shot 2018-08-06 at 1 11 08 pm" src="https://user-images.githubusercontent.com/2225624/43730962-10a824ec-997b-11e8-981d-19b7019819be.png">

**Comment by adabutch** [comment]
screenshots via https://github.com/City-of-Bloomington/drupal-theme-cob/commit/0a2291395609773179af0d6a07848cdca4d14cba

![Screen Shot 2019-07-18 at 1 41 47 PM](https://user-images.githubusercontent.com/2372040/61481366-24c29100-a966-11e9-8686-407291e963ed.png)

![Screen Shot 2019-07-18 at 2 14 20 PM](https://user-images.githubusercontent.com/2372040/61481478-5c313d80-a966-11e9-9db3-e34000ceb32f.png)
