### ISSUE TITLE
Show vacancies on the boards page

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#113]
We need to indicate vacancies visually on the cards of the B/C master page.

**Comment by rbdietz** [comment]
We need to provide a listing of vacancies available on the public website.

**Comment by inghamn** [comment]
We're going to add a class="vacancy" to the info cards listing.  We'll add new CSS to display the board info cards similar to the search results.

**Comment by inghamn** [comment]
The grid of board info cards doesn't provide enough screen space for all the information we want to display about the board.

We want to render the board info cards similar to how search results are displayed.

**Comment by inghamn** [comment]
In our meeting we decided to show the "Vacancies" text in parentheses inline, next to the board title.  This is instead of floating it all the way to the right.  The font should match the board title.
