### ISSUE TITLE
Update link to webtrac in the PROMT integration

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-theme-cob#114]
Our theme adds an "Enroll Now" button for parks programs.  We are launching the new version of WebTrac and need to update the link to the new URL.

**Comment by charlesbrandt** [comment]
The format for the direct link urls in the new version is:

https://webtrac.bloomington.in.gov/wbwsc/webtrac.wsc/search.html?sessionID=<?VSI-SessionID?>&module=AR&

with the following parameters:

Primarycode=81003
Category=XXXX
Type=

Example:
https://webtrac.bloomington.in.gov/wbwsc/webtrac.wsc/search.html?sessionID=%3C?VSI-SessionID?%3E&module=AR&Primarycode=84013
