### ISSUE TITLE
Board or Commission link should be in Related Categories section

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#119]
Currently the link for an associated Board or Commission shows up before the Related Categories section:

For example:

https://bloomington.in.gov/sustainability/

<img width="1252" alt="screen shot 2017-12-20 at 4 52 39 pm" src="https://user-images.githubusercontent.com/2225624/34230476-3bc3fc84-e5a6-11e7-8810-91c5ee84edf0.png">

These should be included in a similar manner as Locations and Departments and show up in the Related Categories section

**Comment by inghamn** [comment]
I'll update the node template.  The board_or_commission field must have been added after we wrote the theme.  Any new fields like this will need to be hard coded into the theme.
