### ISSUE TITLE
Info cards need room for three lines of title

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#12]
Currently we only have room for two lines of title text on an Info Card. This should be increased to room for 3 lines. 
<img width="352" alt="screen shot 2017-05-09 at 10 54 33 am" src="https://cloud.githubusercontent.com/assets/2225624/25857083/f7552868-34a5-11e7-92a1-b1dfbff79e62.png">

**Comment by schnippy** [comment]
Confirming error and validating at:

https://bloomington.in.gov/alpha/housing/home-ownership

Removing height constraint and adding .5 em to the bottom of h3 to enforce space.

**Comment by charlesbrandt** [comment]
Yes, the error shows up on that page too. We'll want to make sure that the title doesn't go past 3 lines. It would be better to truncate in that case. Is that possible to do? If we allow the title to grow beyond 3 lines there are some cards that may only show the title if they're given the chance.

**Comment by rbdietz** [comment]
Should we set a character limit in our content guidelines to mitigate this?





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by schnippy** [comment]
Apologies for the above comment, it was meant to provide more context for the git commit I tried to do following but am still working through access issues on. It did describe precisely what I ended up implementing to address the issue, namely removing the hard-coded height (2em) on the selector:

`.boards-block > div a h3, .departments-block > div a h3, .promt_programs > article a h3, .paragraph--type--info-card a h3`

but I see your point about implementing a text limit as pushing this too far with the headline will only push the content further down in the block, ex: 

![screen shot 2017-05-15 at 11 30 11 pm](https://cloud.githubusercontent.com/assets/439451/26088763/f4955852-39c6-11e7-9c21-65accc67ca4c.png)

If we want to restrict the text, we could add a limit that automatically limits the amount of text the editor has entered for either the title or the description using smart_trim

https://www.drupal.org/project/smart_trim

Or we could set a hard limit and then add maxlength_js to give the user visual cues ("You have 4 characters left...") to help them refine their text to fit.

https://www.drupal.org/project/maxlength

**Comment by charlesbrandt** [comment]
This looks good now in production.
