### ISSUE TITLE
Remove cover image from search page

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#120]
We should review which page layouts do not require a cover image. The search results page is a good example of one that does not need the image. The cover image gets in the way in this context. 

We should also review the size of the cover images in general. We have [received feedback](https://bloomington.in.gov/crm/tickets/view?ticket_id=162880) that they take up too much space.

**Comment by inghamn** [comment]
We now want to do this for all pages

#153
