### ISSUE TITLE
Remove empty alert bar

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#123]
Right now, when there are no alerts showing on the site, there is a persistent pink bar that shows on all pages. This should not be visible when there are no alerts. We may also want to consider updating the color choice for the background color.

**Comment by inghamn** [comment]
This is a result of a Drupa bug that doesn't look like it's going away any time soon.

https://www.drupal.org/node/953034

We might have to redesign the theme to accommodate it.

**Comment by inghamn** [comment]
I think we're going to need to ditch the view, and instead load any alerts in the theme.  That way, the region really will be empty, unless we shove alerts into it.

We're already loading nodes in the theme on the front page (News, About, Mayor).  This would be an additional load in the preprocess_page__front().

This would mean not being able to move the alerts to different regions using the web interface.  It would also completely ignore the view (and view block), so those could be deleted.
