### ISSUE TITLE
Alerts should link directly to the primary link

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#124]
Alerts shown on the homepage currently link to the corresponding alert node. There is a link associated with the Alert content type. It would be ideal if the whole alert linked to the url associated with the node, rather than the alert node itself. 

This will require updates to the way our theme works in order to implement.

**Comment by charlesbrandt** [comment]
Cliff also mentioned it may be possible to move the alert system external system to simplify the way alerts are managed. This is something we can discuss / consider when it's time to implement this update.

**Comment by inghamn** [comment]
Should we remove the date, then?

**Comment by rbdietz** [comment]
Depends.  What is the purpose of the date?





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by inghamn** [comment]
It turns out the date is controlled through editing the content type in the web interface.  There's no custom code needed in order to remove it.

**Comment by charlesbrandt** [comment]
The date indicates the day the content was created. I could see making a case for showing it or hiding it in the case of an alert.

**Comment by inghamn** [comment]
In the web interface you can only control whether to display the date for all alerts.  On a per-alert basis, we'd need to implement another field for that.

**Comment by charlesbrandt** [comment]
All or nothing is fine. Having a date show is a nice reminder for webadmins about how long the Alert has been published. Ideally those won't stick around for months at a time. However, for everyone else, not having a date seems cleaner.

**Comment by charlesbrandt** [comment]
There is a gray bar that is coming from the div#alerts. This only shows up when the screen is wider than the alert article. It may be possible to apply the alert class (e.g. .info) to the parent div.

**Comment by inghamn** [comment]
The alerts area has a background of gray.  Each individual alert will have a different background color.  So it's gray alert area with multicolor alerts showing inside it.
