### ISSUE TITLE
CSS: Not enough room for contact info fields

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-theme-cob#128]
For instance, the email address is getting cut off:

https://bloomington.in.gov/parks/facilities/community-gardening/willie-streeter-community-garden
https://bloomington.in.gov/farmers-market/vendors/american-mushroom-spice-co

**Comment by inghamn** [comment]
This issue is starting to be addressed in #150

**Comment by adabutch** [comment]
current iteration:

<img width="1117" alt="screen shot 2018-07-26 at 8 58 37 am" src="https://user-images.githubusercontent.com/2372040/43264042-000dfd26-90b3-11e8-9267-779d48d5fdbf.png">

<img width="1003" alt="screen shot 2018-07-26 at 9 03 00 am" src="https://user-images.githubusercontent.com/2372040/43264044-001d9056-90b3-11e8-90fd-01181025a01a.png">

<img width="439" alt="screen shot 2018-07-26 at 9 03 16 am" src="https://user-images.githubusercontent.com/2372040/43264046-009caf94-90b3-11e8-9bfa-b5aff0a36eb7.png">

**Comment by inghamn** [comment]
The field that's really problematic to layout is the email address. It's normal for email addresses to be very long, and they look weird when split in half.  The rest of the contact info fields generall have a reasonable width. (Addresses can be edited to use a nice, multi line format).

Would it make sense to put the email address somewhere else on the screen, or somehow give it special treatment?

**Comment by adabutch** [comment]
six items down to one, all fit nicely, closing!
