### ISSUE TITLE
Related Categories should use page titles

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#13]
For the Related Categories section, the links are displayed with the page alias when no title is supplied. For internal links, it would be nice to use the linked page's title instead. For example:

https://bloomington.in.gov/alpha/jobs

<img width="1073" alt="screen shot 2017-05-09 at 11 15 05 am" src="https://cloud.githubusercontent.com/assets/2225624/25858065/caaa394a-34a8-11e7-941f-f649109b4596.png">

**Comment by rbdietz** [comment]
This jobs page should also include parks and public safety jobs pages as
cards





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by charlesbrandt** [comment]
When this change was deployed to production, we're getting the following errors:
![screen shot 2017-05-31 at 4 17 56 pm](https://cloud.githubusercontent.com/assets/2225624/26652120/d91b40f2-461c-11e7-9782-77170bf77d2a.png)

This also shows that the Call to Action buttons are experiencing the same behavior (showing the alias instead of the page title.)

Now a few of the related category links don't show up:
![screen shot 2017-05-31 at 4 18 17 pm](https://cloud.githubusercontent.com/assets/2225624/26652132/e08c16d6-461c-11e7-81d1-d41c8dd09d89.png)

**Comment by schnippy** [comment]
@charlesbrandt - thanks for the catch, I did not see  these errors in my local (perhaps because my error notice levels are too high in ADD) but added a test to prevent them from occurring. 

I do not see the same issue you flagged (missing titles) above with the latest copy of the database from Cliff. I did see it flash briefly as an anonymous user but have not been able to replicate it. That could mean its a caching issue where the database had to catch up -- if this doesn't resolve it, I'm going to try another approach to loading the node object.

**Comment by charlesbrandt** [comment]
I'm not seeing the error any longer, but the but the buttons are still showing the Alias rather than the page title from the referenced page. 
![screen shot 2017-06-01 at 3 53 17 pm](https://cloud.githubusercontent.com/assets/2225624/26698144/b7db00e6-46e2-11e7-81a1-bdc45d3c119e.png)

**Comment by inghamn** [comment]
We're having the problem on Call to Action link fields.  Once we solve this, it needs to be done it both places.

**Comment by inghamn** [comment]
Cannot look in the rendered content array of the link item to do this.  It's already been populated with stuff.  You have dig into the real field object and load the entities from there; updating the content array once you've got a title.
