### ISSUE TITLE
Remove duplicate Google Analytics code

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-theme-cob#131]
The google analytics javascript is showing up twice on city website pages. This may result in double counting traffic. Either way, the duplicate should be removed.

**Comment by rbdietz** [comment]
Please conduct a census of website pages to ensure all key pages are included in analytics, including public apps. R

**Comment by inghamn** [comment]
The Google Analytics code is global.  It is part of the HTML templating and shows up on all pages of the site.
