### ISSUE TITLE
Boards and Commissions pages

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#14]
Remove "Connect with us" and OnBoard links

Listing of committee members on B&C pages needs to include vacancies

Board Documents should not show file name just Agenda, Minutes, Packet, as download link.  Ok for filename (but title is better) for miscellaneous files.

**Comment by rbdietz** [comment]
There needs to be a sensible ordering applied to the board members and for the display of any vacancies. @charlesbrandt See https://bloomington.in.gov/alpha/boards/digital-underground

**Comment by charlesbrandt** [comment]
For staff listings we sort by last name. That seems like a reasonable sort order in this case too.

**Comment by inghamn** [comment]
We now sort board members by lastname
