### ISSUE TITLE
Animal Shelter adoption forms generate too much spam

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-theme-cob#140]
We are not able to sift through the number of adoption applications we are receiving and many potential adopters are not following through, leading to a very messy system.

We should remove the link to apply to adopt cats and dogs. Instead of the links to the forms, we should  add a note to call the adoption center to apply for a specific pet.

**Comment by rbdietz** [comment]
I'm not sure about this.  I think we should keep the adoption buttons.  and
discuss this before making changes.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by inghamn** [comment]
We liked the "Adopt a Pet" buttons, and should add them back.  Instead of them going to a form, though, they should just link to a page of information on how to adopt from the Animal Shelter
