### ISSUE TITLE
People Finder Interface

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#143]
We need to add at people finder interface to the public website.  This should be a search field for submitting first and/on last names and providing a person record from /directory.  This should be a larger pool than our current contact/directory page, but still needs to support removing people if needed.  

Something like this is desired, but we should discuss before implementing to ensure all requirements are agreed.

https://directory.iu.edu/

**Comment by inghamn** [comment]
We published our Directory application to the outside world.
