### ISSUE TITLE
Intro div should go full width when there's no sidebar content

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-theme-cob#145]
If there is no aside content, we want the into div to take up full width.  We'll need to modify the CSS to account for this.

Drupal has a bug, though where it cannot actually check if a render array is empty or not.  So, we'll also need to do a workaround when checking for aside content.

**Comment by adabutch** [comment]
@inghamn FYI - just pushed another commit, (e82308ea93b0f6218323da57fe80ca2cb0bdb77e), which corrects a subtle behavior style bug I missed yesterday. 

I think this does it here, feel free to close this issue as you see fit.
