### ISSUE TITLE
Social media share buttons

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-theme-cob#146]
We think we want to start drawing some social media sharing links.  Probably just "Share on Facebook" and "Share on Twitter" for now.  We'll need to figure out how we want to incorporate this into the theme.

Pages that are shared should have opengraph markup designating a title, description and image.  We'll need to figure out what image to be used for any given page that gets shared from our site.  We might be able to use the content image.  If so, we'd probably want to make the content image a required field, otherwise we wouldn't draw the share buttons.

**Comment by inghamn** [comment]
The Open Graph images that are used should conform to a different aspect ratio than our regular content images.  We might want to have a seperate, additional media element for content types that we want to be able to be shared.

**Comment by inghamn** [comment]
#150

**Comment by adabutch** [comment]
**note:** we can further test facebook/twitter share once master goes live (not internal via rogue)
