### ISSUE TITLE
Update wording for top nav

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#156]
Currently we have "About Bloomington", "City Government", "News & Events", and "Services & Guides".  After launching the new site in 2017, we discussed adjusting these to be:
"Information & Guides", "City Government", "News & Events", and "Top Services" to reflect how they're being used. 
The links can still go to the same destination.

**Comment by adabutch** [comment]
<img width="1070" alt="screen shot 2018-07-27 at 9 31 38 am" src="https://user-images.githubusercontent.com/2372040/43323523-e37abd34-917f-11e8-9989-7ba34586e9ef.png">

@charlesbrandt - if the above looks correct, I can mirror in production.

**Comment by charlesbrandt** [comment]
Perfect! Thank you!

**Comment by rbdietz** [comment]
You will also need to adjust the target pages accordingly.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by adabutch** [comment]
@rbdietz - oh yeah, good looking out!

@charlesbrandt - would you say it's fine to update the page titles accordingly when we ship this?

also - should the `/about` url be changed to perhaps match the new text? eg. `/information`

**Comment by rbdietz** [comment]
I think we need to keep /about, but it might not be the target for this
link.  We should discuss.






Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by adabutch** [comment]
**note:** this will need changes once master goes live

**Comment by adabutch** [comment]
@inghamn / @rbdietz - these changes are live, I can edit the URLs mentioned above to match whatever we desire. LMK 😄

**Comment by rbdietz** [comment]
We should determine if /about is still the target for Guides.  we still
need /about even if the target changes.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by charlesbrandt** [comment]
I think it's okay to leave Information & Guides pointing to the /about page and keeping the title of that page as "About Bloomington". It's a good introduction. From there we quickly start linking to other information and guide style resources. 

If it needs to change, we'll want to consider the implications with the integration with the home page. I know that the "About Bloomington" section pulls some content from /about to be on the home page (at least the content image).

**Comment by adabutch** [comment]
thanks guys!

@charlesbrandt - are we safe to close this issue now then?
