### ISSUE TITLE
Need conditional video button/link in board/commission template

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#16]
We need a link/button to direct to CATS video archive for each specific board/commission, if that archive exists.

Related to https://github.com/City-of-Bloomington/OnBoard/issues/173

**Comment by schnippy** [comment]
I can take this one and the companion ticket at City-of-Bloomington/OnBoard#173 - I can add the field (of type link) and add it to the "Board / Commission" content type and then test for it in the node output. Few questions/clarifications:

- How are you managing content type exports? Are you using planning on using features to export these? If its easier, I can just focus on the theme layer and test for a field ("field_url") and when it exists, it will work. 
- I'm assuming that there is only going to be one archive URL per comission 
-  Natural place for this button seems to be right below the "See Google Calendar" button, ex. "See Past Events"

![screen shot 2017-05-16 at 9 41 42 am](https://cloud.githubusercontent.com/assets/439451/26109184/b20c0098-3a1c-11e7-969d-c2bd11eeea05.png)

**Comment by inghamn** [comment]
This will not be a field in Drupal.  Rather, all of the necessary information will come across the JSON feed from OnBoard.  What that information is, is still up in the air, pending https://github.com/City-of-Bloomington/OnBoard/issues/173
