### ISSUE TITLE
Add prefixes for flexbox properties

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-theme-cob#17]
We've started using flexbox for layout stuff, however, so far, I've only been using the standard CSS3 Flex properties.  It turns out Chrome and Safari both need prefixes to get these to work.

We need to run through and add prefixes to all the uses of flexbox stuff.

**Comment by inghamn** [comment]
We were originally seeing problems with the banner image and breadcrumb layout.  Now that we've redone the CSS for that, I don't know if this is still a problem.   I've checked all the other instances of flexbox CSS, and they're rendering as expected on Firefox, Chrome, and Safari ( both desktop and mobile versions).

I have not tested with IE or Edge, so there might still be some use in adding prefixes for Windows.

**Comment by charlesbrandt** [comment]
Looks good to me on Edge
![banner-breadcrumb-alpha](https://cloud.githubusercontent.com/assets/2225624/26452552/56fae034-412e-11e7-9f0a-73af0fcc4646.PNG)
