### ISSUE TITLE
Show repaired potholes count on homepage

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-theme-cob#174]
We've been keeping track of repaired pothole counts in a spreadsheet.  We want to show the latest total repaired for this year on the homepage.

**Comment by inghamn** [comment]
It's probably easiest to read the total from a CKAN query

**Comment by rbdietz** [comment]
However you want to do it is fine, just make sure the you are alerted if
part of this process isn't working.




Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0076 Cell
bloomington.in.gov

**Comment by inghamn** [comment]
I don't have any mechanism right now for drupal to send me an email whenever somethign goes wrong.  That's another project to tackle.

**Comment by inghamn** [comment]
This code still caused Drupal to crash when there were network problems to CKAN.

**Comment by inghamn** [comment]
The season for potholes is past, and we've removed the posthole count from the front page.

**Comment by rbdietz** [comment]
This will be back next year.  This issue should be fixed before then.

**Comment by inghamn** [comment]
CKAN's datastore has not been able to update, and the spreadsheet's format changed again.  This implementation needs to be redone to not rely on the spreadsheet or CKAN.

**Comment by inghamn** [comment]
The pothole count should have been deleted months ago, since we don't want it displayed.
