### ISSUE TITLE
Search Button Misaligned

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#177]
Search button is misaligned in Chrome for Mac.
![Image 6-14-19 at 2 51 PM](https://user-images.githubusercontent.com/1135994/59531447-f4458e00-8eb3-11e9-824c-5a8d8f5aac40.jpg)

**Comment by adabutch** [comment]
I've noticed this happening periodically too.

Related item(s) worth mentioning: 
- https://github.com/City-of-Bloomington/drupal-theme-cob/issues/149
- The placeholder & input text value do not pass color contrast.
- Focus outline (browser default) is hard to visually distinguish on top of blue/green.

**Comment by inghamn** [comment]
When the archive module is the first to render a page after a cache rebuild, the ID's on the search form input are given different names.  Instead of "edit-actions" and "edit-submit", the archive module causes the render to use "edit-actions--2" and "edit-submit--2"

**Comment by inghamn** [comment]
When some other page is the first render after cache clear, the archive route actually renders invalid HTML.  The search form up at the top of the screen and the data navigation form for the archive listing both have elements with the same ID attribute (which is not valid and will cause CSS problems)

I don't know if we can prevent Drupal from rendering invalid HTML.  Instead, I think we're going to have to try to avoid using the problematic IDs in CSS selectors.

**Comment by adabutch** [comment]
Proposed fix in PR #189
