### ISSUE TITLE
_cob_events function causes error when GCal endpoint is down

### ISSUE THREAD

**Issue by sethCOB** [City-of-Bloomington/drupal-theme-cob#178]
If Google Calendar is down, the page refuses to display and instead returns an error.

For our particular case, I narrowed it down to the _cob_events function in [cob.theme](https://github.com/City-of-Bloomington/drupal-theme-cob/blob/85f8c699610cf771b116191dc70e594be803a366/cob.theme#L84).

Since we were in a hurry, my temporary fix was to just comment out the areas of the main theme that called _cob_events until Calendar services were restored. Introducing error handling into the function would help prevent this from taking down the site in the future.

**Comment by inghamn** [comment]
This is a problem with our Google Calendar module for Drupal.
