### ISSUE TITLE
Update event tile output 

### ISSUE THREAD

**Issue by schnippy** [City-of-Bloomington/drupal-theme-cob#18]
CSS needs updates to fix font sizing and spacing, ex. to make sure content can fit into the cell. 

URL for confirmation: https://bloomington.in.gov/alpha/boards/bicycle-pedestrian-safety

![screen shot 2017-05-15 at 10 08 01 pm](https://cloud.githubusercontent.com/assets/439451/26109226/d6ca2ca2-3a1c-11e7-8d83-e8ae8edfdc85.png)

May be related to discussion regarding optimizing text length in #12.

**Comment by schnippy** [comment]
Taking this one - this is requiring some updates to my local config as the calendar connection fails without the credentials.json 
```
The website encountered an unexpected error. Please try again later.

InvalidArgumentException: file does not exist in Google_Client->setAuthConfig() (line 849 of /Users/gregschnippel/projects/bloomington/vendor/google/apiclient/src/Google/Client.php).
```

Setting this up to point to my local calendar now will update readme in calendar if necessary.

**Comment by inghamn** [comment]
You'll need to sign up for a Google service account and generate a private key credentials file.

Links to documentation are on the calendar module README
https://github.com/City-of-Bloomington/drupal-module-calendar
