### ISSUE TITLE
mobile burger + header nav

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/drupal-theme-cob#187]
On mobile, @inghamn & I have identified a handful of issues to support rethinking the hamburger menu show/hide feature approach.

**eg:**
- tab flow
- menu hidden item selecting
- active/focus/etc states
- relies on checkbox:checked for open/close
- pwa approach towards js last, using as an enhancement
- etc

**Old:**
![Screen Shot 2019-07-17 at 8 22 39 AM](https://user-images.githubusercontent.com/2372040/61375124-16904a00-a86c-11e9-8e86-c7a046c0715d.png)

**New:**
![Screen Shot 2019-07-17 at 9 56 49 AM](https://user-images.githubusercontent.com/2372040/61381659-61fd2500-a879-11e9-9f2a-7d02a00de805.png)

The solution for the time being is to just show the menu. At only four menu items, we have the real estate.

**Comment by adabutch** [comment]
relates to #177

**Comment by inghamn** [comment]
For normal browser sizes, I don't think this is working on pages without a cover image.

https://rogue.bloomington.in.gov/drupal/news/2019/07/08/4138

**Comment by adabutch** [comment]
mostly wrapped up here, closing ... follow via #189
