### ISSUE TITLE
Separate the council subcommittees on the boards page.

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-theme-cob#212]
In order to make a distinction, we want to list the council's standing committees in a separate block from the main list of active boards and commissions.  We should probably label it something like "Council standing committees".

**Comment by rbdietz** [comment]
Use the Label "City Council and Council Standing Committees" R




Rick Dietz (he/him)

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0076 Cell
bloomington.in.gov

**Comment by inghamn** [comment]
So, it's not that they're subcommittees that we care about.  What were going after is that they're related to the Common Council.  We may not need the subcommittee flag, after all; as we already associate boards with departments.  So, we already have these committees associated with the Common Council.

**Comment by rbdietz** [comment]
Did this update happen?

>

**Comment by inghamn** [comment]
Users now have to scroll all the way to the bottom of the page to see the Council and it's subcommittees.  We should provide a navigation link from the top of the page down to the where the Council is listed.

**Comment by rbdietz** [comment]
We should also make sure they aren't pushed several blank pages down as
well.

**Comment by inghamn** [comment]
I think it would make sense to provide table-of-contents links to each section.  I could put the links over in the sidebar.  What should we call the group of boards and commissions that are not council-related?

**Comment by rbdietz** [comment]
"City Boards and Commissions" Is fine.
Links should be below the introductory paragraphs like a ToC.
