### ISSUE TITLE
Update the footer links

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-theme-cob#219]
Connect with us on Social Media
(Facebook Icon) Facebook               
Should link to https://www.facebook.com/citybloomington
(Twitter Icon) Twitter                         
Should link to https://twitter.com/citybloomington
(Instagram Icon) Instagram             
Should link to https://www.instagram.com/citybloomington/
(NextDoor Icon) NextDoor                
Should link to https://nextdoor.com/pages/city-of-bloomington-2
(YouTube Icon) YouTube                  
Should link to https://www.youtube.com/channel/UCjrKAfL1hf92JtpBknUg-GA

**Comment by adabutch** [comment]
Needing icons for:

- [x] NextDoor
- [x] YouTube
