### ISSUE TITLE
Search form display on mobile

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-theme-cob#24]
When mobile devices view the site, the search form does not fit in the available space in the title area.

An idea we've had to solve this was to hide the search form input on mobile sized screens.  We would provide a button to display and hide the search form in a modal dialog at the top.

If that doesn't work, we'll need to figure out some design that will make search usable on mobile.

**Comment by schnippy** [comment]
Could we make the search box hidden by default, as in the model on Drupal.org:

![screen shot 2017-05-25 at 11 21 41 pm](https://cloud.githubusercontent.com/assets/439451/26498231/51495ef8-41fc-11e7-8eca-a257eafed232.png)

Which then z-indexes above the rest of the elements when invoked, saving space without pushing elements around:

![screen shot 2017-05-25 at 11 21 30 pm](https://cloud.githubusercontent.com/assets/439451/26498260/6abce72e-41fc-11e7-90ca-868febfe314f.png)

I'm suggesting this for all viewports, and in mobile this would take 100% of the screen space when invoked.

**Comment by inghamn** [comment]
I think (hidden by default) can be okay if it simplifies things.  We're certainly going to need to have it hidden when there's not space.  Ideally, we would go ahead and show it when there's space.

**Comment by inghamn** [comment]
We think we want to have the search form visible at all times.  When the screen is not wide enough (ie. mobile) The search form would be moved to below the site header.

**Comment by inghamn** [comment]
This has resurfaced in #149
