### ISSUE TITLE
Locations page design

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-theme-cob#26]
We've entered aliases for our Location content types at /location/node-title.   However, we do not have anything being hosted at the /location route.  

We should probably come up with some page that lives at that route.

**Comment by charlesbrandt** [comment]
We can create a view for all locations at /location

**Comment by inghamn** [comment]
I have created the view at /location.  I'm still working on info card styling

**Comment by rbdietz** [comment]
Please create an alias "/locations" that resolves to /location





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by charlesbrandt** [comment]
The zoom level for the map should be zoomed in to show more detail than the current setting. I tried to change this setting for the module here:
https://bloomington.in.gov/alpha/admin/structure/types/manage/location/display
and I tried clearing the cache afterwards, but the setting doesn't seem to have any effect on the rendered map.

**Comment by inghamn** [comment]
I successfully changed the default zoom level to 14 in the field's manage display for the content type.

https://bloomington.in.gov/alpha/admin/structure/types/manage/location/display
