### ISSUE TITLE
Responsive Info Card Spacing

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#27]
Spacing for Info Cards is not working.  For standard desktop browser widths, the display should allow for 3 (or more?) cards in a row to be rendered.  Currently only 2 cards are being displayed in a row for most widths.  This is occurring on most (if not all) pages with Info cards.

**Comment by inghamn** [comment]
Some pages to review:

https://bloomington.in.gov/alpha/services
https://bloomington.in.gov/alpha/departments
https://bloomington.in.gov/alpha/recreation/sports
https://bloomington.in.gov/alpha/asm/animals

How do those look in various browsers?

**Comment by inghamn** [comment]
The layout looks good.
