### ISSUE TITLE
Links should use default colors

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#3]
Looks like common link colors are:

:link { color: #0000EE; }
:visited { color: #551A8B; }

For standard body content, links should show up with this blue and be underlined to make it easier to see links.

**Comment by inghamn** [comment]
Which screen demonstates this?  I'm not seeing this anywhere.  I thought we, in fact, did not want to underline links?

**Comment by charlesbrandt** [comment]
This page has links in the content:
https://bloomington.in.gov/alpha/arts/bead
I'm looping in Sanket on this so he can weigh in on the topic
