### ISSUE TITLE
Making top nav sticky on the top

### ISSUE THREAD

**Issue by schnippy** [City-of-Bloomington/drupal-theme-cob#32]
As discussed, we would like to have the current top navigation float to the top of the page and remain sticky there as the user scrolls down the page. 

![screen shot 2017-05-25 at 10 13 42 am](https://cloud.githubusercontent.com/assets/439451/26453935/7a363e04-4133-11e7-9488-0f3e91391bac.png)

**Comment by schnippy** [comment]
Using the sticky_nav module and updating the classes, its possible to get there for the top bar, but there are some css issues that need to be resolved when this bar is shifted into sticky-state, ex:

![screen shot 2017-05-25 at 10 19 13 am](https://cloud.githubusercontent.com/assets/439451/26453998/a9ba9aa8-4133-11e7-94f9-4d1132e75e6e.png)

Having both the top (url / search) and the icon bar float would seem to be too much so we could try moving smaller versions of these icons into the bar between the url / search, and then have that collapse to a hamburger menu in mobile viewports.

Are there other designs ideas already for how this would work?

**Comment by inghamn** [comment]
The search form also needs a complete CSS overhaul anyway.
See #24 

But why a whole 'nother module?  I was expecting this to be a pure CSS thing in the theme.

**Comment by charlesbrandt** [comment]
There's a lot of debate on if sticky navs are a good pattern or not. I'm a bit on the fence on it. It sounds like Rick wants to run with it, so I'm cueing from that. 

My favorite approach is when you scroll down, the nav disappears completely, but when you scroll up it slides in to view. With this approach we could keep the nav the same on it's corresponding display (single bar + hamburger for mobile, bar + icons for desktop) without worrying about the icons taking up too much space. 

Here are some resources on implementing that approach:

http://wicky.nillia.ms/headroom.js/

https://medium.com/@mariusc23/hide-header-on-scroll-down-show-on-scroll-up-67bbaae9a78c

**Comment by inghamn** [comment]
For what it's worth, I'm not a fan of this javascript approach.  Sites that do this cause my phone's browser to be unresponsive to touch.

**Comment by schnippy** [comment]
I implemented this locally last night with just the stickyjs library, rolling back the sticky_nav module to just implement the library we needed in our theme. I'm reluctant to push it up as it does force a jquery load on every page the theme is used and I understand we are trying to be conservative in our module / library usage. 

I was defaulting to a javascript approach for ease of implementation and because it was simpler to define 'sticky-mode-on' classes for styling but I can try a pure-css approach, perhaps as defined here: 

https://mobiforge.com/design-development/mobile-friendliness-101-how-to-build-a-fixed-navigation-bar

This will need to take into consideration the approach we are pursuing on #24

**Comment by inghamn** [comment]
It seems like we need to implement #24  first, then see what we can do abotu the nav bar.

**Comment by adabutch** [comment]
@inghamn I think we can close this one now? 😄

**Comment by inghamn** [comment]
Yes, I think we can call this one a "won't implement"
