### ISSUE TITLE
Clearer layout for B&C members

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#34]
Right now it's difficult to make the distinction between a person's name and the corresponding details about the seat they're in. Part of this may be caused by the equal line spacing above and below the person's name. The goal is to make the name and seat details part of a more visually coherent block.

**Comment by rbdietz** [comment]
This needs to apply to staff listings for departments too.

**Comment by schnippy** [comment]
Updating to add space, using this page as guide: 

https://bloomington.in.gov/alpha/boards/bicycle-pedestrian-safety

![screen shot 2017-06-02 at 9 36 12 am](https://cloud.githubusercontent.com/assets/439451/26728174/4deef9fe-4777-11e7-8f16-fcd25f99f869.png)

will check for behavior on staff listings.

**Comment by charlesbrandt** [comment]
This is heading in the right direction. At mobile window widths, it looks like it reverts back to the previous behavior and the blocks aren't well defined:
![screen shot 2017-06-05 at 9 03 28 am](https://cloud.githubusercontent.com/assets/2225624/26785785/20528238-49d2-11e7-9f84-dc53b85b7230.png)

Also, at desktop widths, we've lost a few columns in the layout.

![screen shot 2017-06-05 at 9 34 26 am](https://cloud.githubusercontent.com/assets/2225624/26785832/5a98d71c-49d2-11e7-9031-6b0270e71e43.png)

I think there is room for 4-5 columns, as long as the rows are well defined.
