### ISSUE TITLE
Mayor's Bio Card on Front Page

### ISSUE THREAD

**Issue by quarterback** [City-of-Bloomington/drupal-theme-cob#35]
<img width="1315" alt="mayor bio mock" src="https://cloud.githubusercontent.com/assets/4461062/26600399/f1a66f12-4549-11e7-94dd-a6de5ad9d9f6.png">

This is how the actual design of that front page should appear. Bio image to the left, content to the right. I've added the header to break up the space between news and to differentiate it from the text beneath.

**Comment by charlesbrandt** [comment]
Ron, can you include the source for the image and then assign this one to Greg?
