### ISSUE TITLE
Change "Visit Google Calendar" text

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#37]
All "Visit Google Calendar" buttons should be changed to "Visit Calendar"
<img width="482" alt="screen shot 2017-06-01 at 8 57 15 am" src="https://cloud.githubusercontent.com/assets/2225624/26680772/a31929ce-46a8-11e7-9dfc-2cc0697a533a.png">

**Comment by inghamn** [comment]
Updated in the Drupal Calendar module

https://github.com/City-of-Bloomington/drupal-module-calendar/commit/949ee35cafcc004cb523427b9643f800cc3d0496
