### ISSUE TITLE
Municipal Code icon should show up on home page

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#38]
The style changes should be updated in the SASS source files, not the generated CSS.

<img width="308" alt="screen shot 2017-06-01 at 9 07 34 am" src="https://cloud.githubusercontent.com/assets/2225624/26681107/efa811aa-46a9-11e7-8be3-8dc16e1d9601.png">

**Comment by inghamn** [comment]
The new icon needs to flip from blue to white on hover

**Comment by inghamn** [comment]
For some reason, the new code icon is way more pixellated, when its rendered, than the other icons.
