### ISSUE TITLE
Related Categories section

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#4]
The Related Categories section at the bottom of the page should pull in related links from a few different sources:

  - Now that breadcrumbs are gone, any parent topic (not home) could show up here
  - Department and Location could be linked here
  - Pulling from the related links fields directly

**Comment by inghamn** [comment]
Currently the label on the links are the title of the node being linked to.  In the mockups, there are more words being used on the button lables.

Do we want users to be able to set the label for the links, independantly from the page titles?  Where should these custom words be defined?
