### ISSUE TITLE
Alerts should be rendered

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#40]
We have an Alert content type configured in Drupal 8. We had configured our Drupal 7 instance to display these in the page header when present. 

Ron, please add renderings / mockups of how these should look as a starting place for this issue.

**Comment by quarterback** [comment]
<img width="722" alt="screen shot 2017-06-12 at 9 40 01 am" src="https://user-images.githubusercontent.com/4461062/27036495-000a6bcc-4f53-11e7-9296-5350a263cd78.png">

**Comment by charlesbrandt** [comment]
Thanks for the rendering. Now we can work to make sure that alert content nodes will show up this way.

**Comment by charlesbrandt** [comment]
I believe alert content types are showing up on the home page.
