### ISSUE TITLE
Edit screen does not use Admin theme for regular users

### ISSUE THREAD

**Issue by quarterback** [City-of-Bloomington/drupal-theme-cob#41]
<img width="1079" alt="screen shot 2017-06-01 at 10 54 54 am" src="https://cloud.githubusercontent.com/assets/4461062/26685675/c7c21938-46b8-11e7-9b5e-460cab68ef89.png">

**Comment by inghamn** [comment]
This apparently happens for non-admin user accounts

**Comment by inghamn** [comment]
I updated the configuration so that regular users see the same theme that Admins do, when editing a page.
