### ISSUE TITLE
Animal Shelter Pages

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#44]
Animal page content needs to be designed/formatted.  Individual animal pages need to go somewhere  or have a call to action button like "Adopt me!" some users can take action.

**Comment by rbdietz** [comment]
Is this pushed?

**Comment by inghamn** [comment]
Yes

**Comment by rbdietz** [comment]
There is nothing on the individual animal pages.  That's the purpose of
this issue.  https://bloomington.in.gov/alpha/animal-shelter/animals/56040

Am I missing something?  If not, then please thoroughly re-read issues
before closing them.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by charlesbrandt** [comment]
We are waiting for feedback from the animal shelter on what information they would like to show on the animal detail pages.

**Comment by rbdietz** [comment]
Prior to getting that feedback we can put an action button on these pages.
I'm less concerned about the fields and formatting than I am about the
pages being a dead-end without an action step.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by rbdietz** [comment]
Add Action Button to adopt, please

**Comment by charlesbrandt** [comment]
An action button to adopt has been added to animal details pages:

https://bloomington.in.gov/animal-shelter/animals
