### ISSUE TITLE
Reduce white space on homepage/elsewhere

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#45]
Let's experiment with a little less whitespace.  Can we we see with 50% or 2/3 of the current spacing looks like?

![screen shot 2017-06-02 at 10 25 43 am](https://cloud.githubusercontent.com/assets/1135994/26730259/4b05f47a-477e-11e7-885c-9bbcb3bad342.png)

**Comment by quarterback** [comment]
Add link to "Government" section header on home page like other headers

**Comment by inghamn** [comment]
Do we still want to reduce the whitespace shown in this issue?  It's a single CSS property.

**Comment by rbdietz** [comment]
Yes, I'd like to see some display options with reduced whitespace.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov
