### ISSUE TITLE
Homepage News and Calendar Blocks

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#47]
If the News blocks and the Events blocks are all going to be a fixed height then we should ensure that the News and Events areas are the same total height and align with each other.  We probably need to reduce the news blocks a few pixels to even this up.

**Comment by rbdietz** [comment]
There is still a several pixel difference between the bottom news event and
the bottom calendar event.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by inghamn** [comment]
I've got it down to a single pixel difference between the two.  I cannot spread that difference out across 4 events.

**Comment by rbdietz** [comment]
Diff isn't a single pixel in Chrome.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by inghamn** [comment]
Chrome is showing a 2px difference.  It's going to vary from browser to browser, depending on how they split up the change.  We're stretching 4 events across 3 news items.  This ends up with floating point rounding problems.

**Comment by inghamn** [comment]
I've got it down to a 1px difference between the browsers I've checked (Linux/Firefox Linux/Chrome Mac/Safari)
