### ISSUE TITLE
Hours not pulling complete list of days

### ISSUE THREAD

**Issue by autrice** [City-of-Bloomington/drupal-theme-cob#48]
https://bloomington.in.gov/alpha/locations/olcott-park  (missing Thurs-Sun) 

https://bloomington.in.gov/alpha/parks/parks-and-trails/bryan-park (missing Sat and Sun which are on the same line in the data input box). I did this intentionally to see what would happen.

There's something about line returns or spacing that's pulling in the data

**Comment by inghamn** [comment]
That is correct, the days must be on separate lines to be formatted correctly.  This is as intended.
