### ISSUE TITLE
Hours layout for locations

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#52]
For location pages, the hours block should always show up below the map. There should not be bullets on the list. The day of the week should be spelled out fully. The day of the week should be in a separate column from the times so that both can be aligned independently. There should be padding between the two columns to make a distinction between them. Day of the week column could be left aligned or right aligned. The times column should be left aligned. If there is no time specified for a day, the time should read "Closed" for that day.

**Comment by inghamn** [comment]
How about doing it rendered as a table, like this:
http://aoi.bloomington.in.gov/drupal/parks/parks-and-trails/bryan-park

**Comment by charlesbrandt** [comment]
Yes, I think that looks much better. Thanks!
