### ISSUE TITLE
uReport integration

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#57]

**Comment by rbdietz** [comment]
This needs to be online ASAP.  Also, a number of current website pages use uReport one-pagers for reporting issues... CFRD, HAND, etc.

**Comment by charlesbrandt** [comment]
As a temporary solution, for general reporting, we can use the direct open311 proxy page available here:

https://bloomington.in.gov/open311-proxy/embed?client=2

Is there content on the new alpha site still using the "one-pagers" approach? Can you provide links to those pages on this thread?

We can work on embedding this in a page.

**Comment by rbdietz** [comment]
Here's one.  I'm not sure about the others, but I'm pretty sure there are a
few the departments use...
http://bloomington.in.gov/report-graffiti







Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by charlesbrandt** [comment]
uReport currently works, but there is more that we would like to do to better integrate uReport with the new site. We could track those issues and features on the uReport project directly (https://github.com/City-of-Bloomington/uReport), but the one page ones (e.g. graffitti) mentioned above are more content specific.

**Comment by inghamn** [comment]
We definitely need to write a Drupal module for uReport.  City staff should be able to specify a category in uReport so that Drupal renders the proxy form for that category.
