### ISSUE TITLE
myBloomington Updates

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#58]
Fix broken links / broken images (for launch)
Update myBloomington to current look/feel

**Comment by laurahaley** [comment]
The Historic District, Neighborhood Association Economic Development results should be in their own sections similar to Trash Pickup and Parking Permits and not About section so they too can have the ability to link more information.  Perhaps this comments goes in the myBloomington project...

**Comment by rbdietz** [comment]
MyBloomington is not connecting.
Also need to make sure mayor and other elected officials images are rendering.

**Comment by rbdietz** [comment]
Images are broken for council members.

**Comment by rbdietz** [comment]
Mayor doesn't have contact info.  Council members are listed with pagers.  The map image should link to the interactive council district map when clicked.

**Comment by laurahaley** [comment]
Historic District information missing from new version.

**Comment by rbdietz** [comment]
Council members are listed with Fax numbers.  
Clerk image and info is missing.
Elected officials info blocks should link to their pages on the website
Add Historic information

**Comment by rbdietz** [comment]
District reps are listed with a "pager" number.  This needs to be fixed.  
District map should link to interactive district map.

**Comment by quarterback** [comment]
Pager is now "office"
Clerk image was fixed.
Linking council bios to mybloomington is going to be tricker because of how it was built.
