### ISSUE TITLE
If all fields on an info card are empty, do not display the card

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#6]
In the case of a guide page with an info card that with all empty fields, the info card should not be displayed.

for example:
https://bloomington.in.gov/alpha/utilities/information

**Comment by charlesbrandt** [comment]
Fair enough... thanks!

**Comment by rbdietz** [comment]
It's not clear what you mean by delete.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov
