### ISSUE TITLE
Tyler Transparency

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#60]
Website Needs to be connected as a card to Gov't, Controller, City Budget pages
Needs to be added to Data Portal - featured on data portal homepage with thumbnail

http://transparency.tylertech.com/bloomington/Pages/

**Comment by charlesbrandt** [comment]
I have added a link on the following pages:

https://bloomington.in.gov/alpha/city/budget
https://bloomington.in.gov/alpha/departments/controller

I plan to replace the City Budget image on the home page with a screenshot of the Transparency module.

**Comment by charlesbrandt** [comment]
I've updated the text on the budget and controller pages. I was referring to the data portal home page.

**Comment by rbdietz** [comment]
Great, thanks.
