### ISSUE TITLE
Reduce prominance of trails in interactive maps

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#61]
Having trails present is ok: b-line and parks trails, but we need to reduce the prominence so it's not the most prominent thing in all of the maps.

**Comment by rbdietz** [comment]
maybe set opacity to 50%?

**Comment by charlesbrandt** [comment]
I think this is something that Laura configures.

**Comment by laurahaley** [comment]
I've toned down the trails for all the maps except the Parks and Bike&Ped map.  Let me know if you would like more adjustments

**Comment by rbdietz** [comment]
Take a look at District 1 and 3 of the Council Maps.  Still seems abil high
intensity.

Also, what is Nmap about?





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by laurahaley** [comment]
I toned it down some more on the council map. Its the background colors making it stand out more. I can remove them all together like I did with the Leaf Map and Paving Schedule map.

The Nmap is the test map for the mapbox style. I'll remove it.
