### ISSUE TITLE
News Release Formatting

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#63]
This 3-column approach doesn't work.

https://bloomington.in.gov/alpha/news/2017/05/25/756

Can we wrap the body text around the image so the text isn't in one super long column?

**Comment by rbdietz** [comment]
2-column is fine.  It just doesn't work when there is 3 columns.

**Comment by adabutch** [comment]
closing this issue out as it's more or less a duplicate of #109 ... generally easier to follow along in a single ticket, feel free to reopen if need be.
