### ISSUE TITLE
OOTM Calendar

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#64]
This calendar needs to list the Mayor's public calendar events.  Please fix ASAP.

https://bloomington.in.gov/alpha/departments/office-of-the-mayor

**Comment by charlesbrandt** [comment]
I verified that the calendar string is the same one as on:
https://bloomington.in.gov/alpha/mayor
It works on the mayor's page... maybe this has something to do with calendars on the department content type template?

**Comment by inghamn** [comment]
This is a per content type setting.
It is a display setting on the calendar field in the content type.  The display settings control how many days of events to get from google, as well as a maximum number of events to render.

**Comment by inghamn** [comment]
I bumped the [calendars on department pages] up to events from 30 days out.  Still a max of 4

**Comment by rbdietz** [comment]
Let make sure there are 4 showing up.  Elizabeth is entering more in July.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by charlesbrandt** [comment]
I bumped it up to 62 days out, max of 4. Currently there are only 2 events on the calendar, so we will not see more until others are added.
