### ISSUE TITLE
Staff listings and board members don't fit available space

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-theme-cob#66]
The four-across thing for staff listings isn't giving enough room for the actual text in the listing.  We either need to shrink the font, or give them more width, and let them be three across.
![screen](https://user-images.githubusercontent.com/630282/26932350-3efad7ce-4c31-11e7-9cea-02812be80219.png)

**Comment by rbdietz** [comment]
Shrink the font for the email addresses





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by inghamn** [comment]
How does this look?

http://aoi.bloomington.in.gov/drupal/departments/esd

**Comment by charlesbrandt** [comment]
That looks good at full desktop width. At smaller window widths it would be good to drop down to 3 then 2 columns ideally.

**Comment by rbdietz** [comment]
mutchles@bloomington.in.gov is overlapping, so maybe a little smaller





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by charlesbrandt** [comment]
this is related to #34

**Comment by inghamn** [comment]
Okay, we are at the smallest font size declared in our theme.  I've expanded the size of the box, so it goes down to three wide, and then two.  This also applies to the board pages in #34 

http://aoi.bloomington.in.gov/drupal/departments/esd
http://aoi.bloomington.in.gov/drupal/boards/park-commissioners
