### ISSUE TITLE
Council Member Public Calendars

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#68]
https://bloomington.in.gov/alpha/council/sandberg

Council members should have public calendars for their constituent meetings and the like.  This should show up on their profile page.  Not a priority for release.

**Comment by inghamn** [comment]
The website supports this.  We need to link each page to each council member's Google Calendar.  Do they each actually maintain a Google Calendar?

**Comment by rbdietz** [comment]
This needs to be reviewed with Dan/Stacy Jane to see if any members want to
do this.  It was an idea we discussed but didn't original from the Council
or members.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov
