### ISSUE TITLE
City Logo

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#69]
The City logo is not present on the website.  Nor is "Bloomington" displayed in any prominent way.  We need to think about how best to remedy this.

**Comment by inghamn** [comment]
Do we want to add the logo to the top-center of the page, like in the mockups?  If so, where should we stick the feedback link?

**Comment by quarterback** [comment]
![logo_banner](https://user-images.githubusercontent.com/4461062/26942863-a0eab150-4c51-11e7-8173-065702e2b250.png)

One proposal.

**Comment by quarterback** [comment]
![option2](https://user-images.githubusercontent.com/4461062/26942932-da42a0fc-4c51-11e7-9e42-f3d9921e2548.png)

**Comment by rbdietz** [comment]
I'd be fine to see how it looks in the center as designed.  Feedback could
shift up closer the the search field.  We should also make the text in the
field say "Search..." or "Search website"





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by rbdietz** [comment]
I'm not super keen on those fonts as first pass.  How about the logo with
the same treatment at the icons in the white bar and placed in the center
there?  Or the logo over the homepage banner, but only on the hompage?
Just throwing out ideas.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by quarterback** [comment]
![screen shot 2017-06-08 at 3 34 43 pm](https://user-images.githubusercontent.com/4461062/26947364-7ed9a0d0-4c60-11e7-8475-5fd2beac45ea.png)
