### ISSUE TITLE
Language Presentation

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#71]
We need to flesh out language based content negotiation.
Old site: https://bloomington.in.gov/languages/

**Comment by inghamn** [comment]
We are not using language negotion on the Drupal site.  For pages that have language content other than English, staff just write the content in the language.  Drupal has no knowledge of a page having multiple translations.

HAND is the largest producer of foreign language content.  I have not had any requests to support separate translations of pages in mupltiple languages.

https://bloomington.in.gov/latino

**Comment by rbdietz** [comment]
Does Drupal support content negotiation for language?  There are some pages
particularly in CFRD that could use this.  WE had this in the old homegrown
site.  R

**Comment by inghamn** [comment]
Drupal does support content negotiation for languages.  It's just that no one has used that feature on the new site.  As far as Drupal knows, all our pages are only available in English.

**Comment by rbdietz** [comment]
There aren't pages with alternative language content, because we have not
informed anyone that this is possible.  CFRD might take advantage of this
as they did in the previous website.  R
