### ISSUE TITLE
Navigation through board meetings

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#77]
Should the URL for this....

https://bloomington.in.gov/alpha/onboard/2/2016

be this?

https://bloomington.in.gov/alpha/meetings/2/2016

**Comment by rbdietz** [comment]
We need to spend some time to design these pages.  There is a lot of wasted space.
https://bloomington.in.gov/alpha/boards/digital-underground/meetings

Back, Next, and the years are just thrown up there.  We might consider some icons for minutes, agendas, packets.

**Comment by inghamn** [comment]
https://github.com/City-of-Bloomington/drupal-module-onboard/issues/17

**Comment by adabutch** [comment]
closing via #180 PR
