### ISSUE TITLE
Board calendars

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#80]
The Calendar event blocks on the Board home pages should link to the meetings page with an #anchor to take users to the exact calendar event (with packet, agenda, etc.)

https://bloomington.in.gov/alpha/boards/plan

**Comment by rbdietz** [comment]
https://bloomington.in.gov/boards
This page had only one meeting listed and there are 10 meetings in the next 3 days.  We should always show at least 3 events.

**Comment by inghamn** [comment]
This was fixed by updating the configuration settings for the meetings calendar display.  The current settings are max of 4 events pulled from the next 90 days.
