### ISSUE TITLE
Feedback form

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#83]
Adjust feedback form to remove "alpha" language and adjust as needed for regular website feedback.  We probably want to route people to the uReport website form instead.

**Comment by charlesbrandt** [comment]
Alpha language has been removed from google form. Now that uReport has stabilized, we can redirect the feedback button to ureport's "website and mobile app feedback" category.

**Comment by charlesbrandt** [comment]
We have been using uReport to successfully capture website feedback.
