### ISSUE TITLE
Action Button

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#85]
Add action button to the mayor section of home page.

Add link to "Government" section header on home page like other headers

**Comment by quarterback** [comment]
the action button on mayor's page is done. the links to below navigation sections of the site (re: govt & services) cause some issues that are related to styling. I'm going to tackle that along with the spacing issues in #45, but it's coupled with some CSS changes I'm working on. Merging this issue with #45
