### ISSUE TITLE
Farmers Market Vendor Page type

### ISSUE THREAD

**Issue by autrice** [City-of-Bloomington/drupal-theme-cob#9]
Create a page type for a vendor that we can aggregate together?

**Comment by inghamn** [comment]
This might best be a page with a CKAN integration

**Comment by charlesbrandt** [comment]
It sounds like Parks & Recreation would prefer to stop tracking vendors on the site. We can confirm later.

**Comment by charlesbrandt** [comment]
Another potential point of integration for this would be Market Bucks, but not all vendors accept Market Bucks. 

The Farmer's Market season is coming up, and Parks was getting started on the process of creating basic pages for each vendor. These would be difficult to sort our later. For now I have created two page types in Drupal: Vendor - Farm and Vendor - Prepared Food. A list of these can be automatically populated on a page using a View. If we get to the point of tracking this in a different system, it will be easy to identify all content of this type and migrate it. Similarly, if the content grows stale and neglected, it will be easy to prune it from other content.
