### ISSUE TITLE
Parks pages with no content

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#92]
Some missing content?
https://bloomington.in.gov/recreation/camps/kid-city-summer

**Comment by charlesbrandt** [comment]
These are all controlled by Promt. If Parks staff have not tagged any programs for this category, then nothing will show up. I know Sports -> Swimming has been tagged correctly. 

The category pages are actual pages in Drupal. This is the boundary between one system (drupal) and the other (Promt). 

I think the best we could do would be to add a field to Parks Category content types that is toggle visibility. We may be able to configure the view that renders the categories to only show those that have been manually specified to show on the site.
