### ISSUE TITLE
Mayor's Public Calendar

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#94]
mayor's calendar needs to show more events.  At least 4 all of the time at /mayor and  /ootm

**Comment by charlesbrandt** [comment]
I extended the range for department pages in #64, but I didn't extend the range for person pages. Person pages now look 62 days out and max out at 4 events. As long as there are 4 events in the next 2 months, the drupal calendar will show 4. Thanks for catching that.
