### ISSUE TITLE
Revisions not working

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#99]
When looking at a node's revision history, the following error is shown:

The website encountered an unexpected error. Please try again later.
Error: Call to a member function getType() on string in Drupal\archive\Breadcrumb\BreadcrumbBuilder->applies() (line 24 of modules/contrib/archive/src/Breadcrumb/BreadcrumbBuilder.php).

https://bloomington.in.gov/node/711/revisions/4243/view

**Comment by inghamn** [comment]
Fixed in archive module
